### PR TITLE
Fixing link

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @HollyAdele 

just fixing a link for Finch Robot

Cheers!

### CODE REVIEW

**Comment by HollyAdele** [comment]
Thanks! 

Did you check them all, or just Finch Robot?

**Comment by spekulatius** [comment]
Hey @HollyAdele 

I've only looked at that one. 

Cheers,
Peter

**Comment by HollyAdele** [comment]
Okay, thank you!

**Comment by spekulatius** [comment]
No worries :+1:

**Pull request merged**
