### PR TITLE
Add Vuo to the "Upper Elementary" list

### PR DESCRIPTION
**Pull request by smokris**

### CODE REVIEW

**Comment by HollyAdele** [comment]
This is awesome!  Thank you so much for taking the time to tell me about it. 

I was hoping this list would have resources to teach kids to program, though.

**Comment by jlstrecker** [comment]
Hi, @HollyAdele. Vuo is a visual programming environment, something like Scratch. You put together the building blocks somewhat differently (Scratch is more about visualizing the control flow, whereas Vuo is more about visualizing the data flow), but it's the same basic idea. I think any kid who could handle Lego Mindstorms or Swift Playground could also manage Vuo. Is there more information that @smokris or I could provide that might make Vuo an appropriate addition to your awesome list?

**Comment by HollyAdele** [comment]
Can you link me to a short demo of someone using the interface?

**Comment by jlstrecker** [comment]
Sure, here's one — https://vimeo.com/148035691

**Comment by HollyAdele** [comment]
Is it only for Macs?

**Comment by HollyAdele** [comment]
Let me know if you come up with a kids version, which ideally would include these features:

-chromebook accessible
-picture based
-immediately intuitive, and not tutorial based
-trade some powerful features for simplicity

I really love your free trial method (unlimited use, no saving feature).  

I'm sorry it didn't work out for this list; I hope you find an awesome list for your software to live on.

**Comment by jlstrecker** [comment]
Ah well. I appreciate your taking the time to explain your criteria.

**Pull request closed without merging**
