### PR TITLE
Add zzz.dog

### PR DESCRIPTION
**Pull request by Asalle**

### CODE REVIEW

**Comment by HollyAdele** [comment]
I'm not sure this resource was intended to teach children to code.

**Comment by Asalle** [comment]
I'm teaching my brother with it and it's the most successful tool so far! It's bright and easy with codepen.io 🙂

**Comment by HollyAdele** [comment]
How old is your brother?

**Comment by Asalle** [comment]
11, 7th grade

**Comment by HollyAdele** [comment]
Cool!

My awesome list is aimed at elementary school kids. Maybe submit it to
another list about learning programming?

**Comment by Asalle** [comment]
Sure! Thanks!

**Pull request closed without merging**
